// Descriptions generated by ChatGPT
const softwareCards = [
	{
		name: 'Krita',
		id: 'catalogueCardKrita',
        img: 'https://mindjam.org.uk/wp-content/uploads/2025/02/Krita.png',
		imgAlt: 'Krita icon',
        description: 'A free, open-source digital painting program designed for artists. It excels at illustration, concept art, comics, and texture painting, with strong brush engines and layer tools. Best if you have a tablet!',
		url: 'https://krita.org/en/',
	},
	{
		name: 'Obsidian MD',
		id: 'catalogueCardObsidian',
        img: 'https://forum.obsidian.md/uploads/default/original/3X/9/f/9f1b5b46aed533f5386cf276ab2cdce48cbd2e25.png',
		imgAlt: 'Obsidian MD icon',
        description: 'A powerful note-taking and knowledge-management app that uses plain-text Markdown files. It focuses on linking ideas through a “knowledge graph” and is highly customizable with plugins.',
		url: 'https://obsidian.md/',
	},
	{
		name: 'Audacity',
		id: 'catalogueCardAudacity',
        img: 'https://cdn.icon-icons.com/icons2/159/PNG/256/audacity_22426.png',
		imgAlt: 'Audacity icon',
        description: 'A free, open-source audio editing and recording program. It’s great for basic to intermediate audio work like cutting, cleaning, analyzing, and mixing recordings. Best if you have a microphone!',
		url: 'https://www.audacityteam.org//',
	},
	{
		name: 'OBS',
		id: 'catalogueCardOBS',
        img: 'https://cdn.icon-icons.com/icons2/3053/PNG/512/obs_macos_bigsur_icon_189890.png',
		imgAlt: 'OBS icon',
        description: 'Short for Open Broadcaster Software. Free, open-source software for video recording and livestreaming. It lets you combine sources like webcams, screens, and audio into scenes for streaming or capturing content.',
		url: 'https://obsproject.com/',
	},
	{
		name: 'Musescore',
		id: 'catalogueCardMusescore',
        img: 'https://production-v2.muse-cdn.com/cdn-cgi/image/w=192,q=50,f=webp/application-icon-images/c729374d-ca11-4dd1-8597-4b1561266039.png',
		imgAlt: 'Musescore icon',
        description: 'A free, open-source music notation program. It allows you to write, edit, and play back sheet music, supporting many instruments and professional engraving features.',
		url: 'https://musescore.org/en',
	},
	{
		name: 'Twine',
		id: 'catalogueCardTwine',
        img: 'https://www.kindpng.com/picc/m/706-7060361_twine-games-logo-hd-png-download.png',
		imgAlt: 'Twine (interactive fiction creation software) icon',
        description: 'A free tool for creating interactive, choice-based stories and text adventures. It uses a simple visual interface and requires no coding, though it can be extended with HTML, CSS, and JavaScript. A perfect start, if you’ve never made a game before!',
		url: 'https://twinery.org/',
	},
	{
		name: 'Godot',
		id: 'catalogueCardGodot',
        img: 'https://cdn.icon-icons.com/icons2/3053/PNG/512/godot_macos_bigsur_icon_190137.png',
		imgAlt: 'Godot icon',
        description: 'A free, open-source game engine for 2D and 3D games. It features a node-based scene system, an intuitive editor, and its own scripting language (GDScript), plus support for C#, visual scripting, and more. Great for more advanced game creation!',
		url: 'https://godotengine.org/',
	}
];

export default softwareCards;