// Descriptions generated by ChatGPT
const softwareCards = [
	{
		name: 'Krita',
		id: 'catalogueCardKrita',
        img: './icons/krita.png',
		imgAlt: 'Krita icon',
        description: 'A free, open-source digital painting program designed for artists. It excels at illustration, concept art, comics, and texture painting, with strong brush engines and layer tools. Best if you have a tablet!',
		url: 'https://krita.org/en/',
	},
	{
		name: 'Obsidian MD',
		id: 'catalogueCardObsidian',
        img: './icons/obsidian.png',
		imgAlt: 'Obsidian MD icon',
        description: 'A powerful note-taking and knowledge-management app that uses plain-text Markdown files. It focuses on linking ideas through a “knowledge graph” and is highly customizable with plugins.',
		url: 'https://obsidian.md/',
	},
	{
		name: 'Audacity',
		id: 'catalogueCardAudacity',
        img: './icons/audacity.png',
		imgAlt: 'Audacity icon',
        description: 'A free, open-source audio editing and recording program. It’s great for basic to intermediate audio work like cutting, cleaning, analyzing, and mixing recordings. Best if you have a microphone!',
		url: 'https://www.audacityteam.org//',
	},
	{
		name: 'OBS',
		id: 'catalogueCardOBS',
        img: './icons/open-broadcaster-software.png',
		imgAlt: 'OBS icon',
        description: 'Short for Open Broadcaster Software. Free, open-source software for video recording and livestreaming. It lets you combine sources like webcams, screens, and audio into scenes for streaming or capturing content.',
		url: 'https://obsproject.com/',
	},
	{
		name: 'Musescore',
		id: 'catalogueCardMusescore',
        img: './icons/musescore.png',
		imgAlt: 'Musescore icon',
        description: 'A free, open-source music notation program. It allows you to write, edit, and play back sheet music, supporting many instruments and professional engraving features.',
		url: 'https://musescore.org/en',
	},
	{
		name: 'Twine',
		id: 'catalogueCardTwine',
        img: './icons/twine.png',
		imgAlt: 'Twine (interactive fiction creation software) icon',
        description: 'A free tool for creating interactive, choice-based stories and text adventures. It uses a simple visual interface and requires no coding, though it can be extended with HTML, CSS, and JavaScript. A perfect start, if you’ve never made a game before!',
		url: 'https://twinery.org/',
	},
	{
		name: 'Godot',
		id: 'catalogueCardGodot',
        img: './icons/godot.png',
		imgAlt: 'Godot icon',
        description: 'A free, open-source game engine for 2D and 3D games. It features a node-based scene system, an intuitive editor, and its own scripting language (GDScript), plus support for C#, visual scripting, and more. Great for more advanced game creation!',
		url: 'https://godotengine.org/',
	}
];

export default softwareCards;